language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: bionic
      sudo: required
    - os: linux
      compiler: gcc
      dist: xenial
      sudo: required

git:
  submodules: false

python:
  - "3.6"

before_install:
  - export cwd=$(pwd)
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cwd=$(pwd -W); fi
  - echo "CWD=$cwd"
  - export SCRIPTS=$cwd/travis
  - export TEST_DIR=$cwd/svzerodsolver
  - pip install --user numpy
  - sudo python setup.py install

script:
  - $SCRIPTS/travis_result_test.sh
