language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: bionic
      sudo: required
    - os: linux
      compiler: gcc
      dist: xenial
      sudo: required

git:
  submodules: false

python:
  - "3.6"

before_install:
  - export cwd=$(pwd)
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cwd=$(pwd -W); fi
  - echo "CWD=$cwd"
  - export SCRIPTS=$cwd/travis
  - export TEST_DIR=$cwd/svzerodsolver
  - choco install python --version 3.8.0
  - pip3 install --upgrade pip
  - pip3 install --user numpy
  - pip3 install --user scipy
  - python3 setup.py install --user

script:
  - $SCRIPTS/travis_result_test.sh
