language: python

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: bionic
      sudo: required
    - os: linux
      compiler: gcc
      dist: xenial
      sudo: required

python:
  - "3.6"

before_install:
  - export cwd=$(pwd)
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cwd=$(pwd -W); fi
  - echo "CWD=$cwd"
  - export SCRIPTS=$cwd/travis
  - export TEST_DIR=$cwd/svzerodsolver

install:
  - pip install -r requirements.txt
  - python3 setup.py install

script:
  - $SCRIPTS/travis_result_test.sh
