language: python

matrix:
  include:
    - os: linux
      python: 3.6
    - os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - os: windows
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6
        - python -m pip install --upgrade pip

before_install:
  - export cwd=$(pwd)
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cwd=$(pwd -W); fi
  - echo "CWD=$cwd"
  - export SCRIPTS=$cwd/travis
  - export TEST_DIR=$cwd/svzerodsolver

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - python3 setup.py install

script:
  - $SCRIPTS/travis_result_test.sh
