[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = """
    --cov-report=html
    --cov-report=term
    --cov=svzerodsolver
    --verbose
"""
