name: Test
on: [push, pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          conda install pip
          python setup.py install
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          pytest --cov --cov-report=term --cov-report=html
      - name: Save coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: htmlcov
