name: Test
on: [push, pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          conda install pip
          pip install pytest pytest-cov pytest-mock
          pip install -e .
      - name: Run pytest
        run: |
          pytest
      - name: Save coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: htmlcov
